### ISSUE TITLE
Syntax and Index error

### ISSUE THREAD

**Issue by erober26** [cognitive-catalyst/watson-beat#17]
I am trying to run this program but it keeps getting stuck at the "DJ MEL Starts" part of the code and then spits out a few errors shown in the screenshot below.

I am using Python 2.7.14 rcl and running on Win 10. 

![image](https://user-images.githubusercontent.com/21028073/45400349-65000700-b611-11e8-9773-1c057211dd16.png)

Any suggestions on this?

Thanks,

**Comment by amchaney** [comment]
Hi Eric, that is super frustrating!  It looks like it is failing in the "mididump.py" script, which unfortunately was something that was just picked up from the internet.  The whole midi input/output needs to be revamped (which is why we are still on python 2.7 instead of 3.6), and is just waiting on some free time.  I know other windows users have been able to get this to successfully work, so I'm summoning @dza6549 or @AdaptiveStep or @michaela10c because i think they may have some advice? 

I'm running on Mac OSX with Python 2.7.13 ... so I can't reproduce your error.  It _might_ be worth trying to try 2.7.13, but I can't promise anything.

**Comment by AdaptiveStep** [comment]
Yes you can successfully run it on windows if you run the script on Cygwin (which is an emulated unix environment on windows).

**Comment by magwa101** [comment]
I have this problem on OS X 10.13.6, Python 2.7.15 using a midi file extracted from a region from Logic

**Comment by mdburke** [comment]
I also have this problem running on Mac 10.13.6 and Python 2.7.12 using the default midi files. Will see if I can come up with a solution

**Comment by mdburke** [comment]
Pull request is submitted for this fix. You could also easily update this temporarily yourself locally using the above fix if you are still hitting this issue.
